export const environment = {
    production:false,
    backendProductHost:"http://localhost:8888/inventory-service/api/v1/products",
    backendCustomerHost:"http://localhost:8888/customer-service/api/v1/customers",
    backendPaymentHost:"http://localhost:8888/payment-service/api/v1/payments",
    backendPaymentBillHost:"http://localhost:8888/payment-service/api/v1/payments/bills",
    backendOrderHost:"http://localhost:8888/order-service/api/v1/orders",
    backendOrderProductsHost:"http://localhost:8888/order-service/api/v1/orders/products",
    backendOrderCustomerHost:"http://localhost:8888/order-service/api/v1/orders/customers",
    backendOrderUpdateHost:"http://localhost:8888/order-service/api/v1/orders/update",
    backendOrderCancelHost:"http://localhost:8888/order-service/api/v1/orders/order",
    backendOrderStatusHost:"http://localhost:8888/order-service/api/v1/orders/status",
    backendOrderCreatedHost:"http://localhost:8888/order-service/api/v1/orders/customer",
    backendBillHost:"http://localhost:8888/billing-service/api/v1/bills",
    backendBillHostId:"http://localhost:8888/billing-service/api/v1/bills/bill",
    backendBillExportHost:"http://localhost:8888/billing-service/api/v1/bills/export",
    backendDeliveredCommandtHost:"http://localhost:8888/delivered-command-service/api/v1/delivers",
    backendDeliveredQuerytHost:"http://localhost:8888/delivered-query-service/api/v1/delivers",
    backendShippingtHost:"http://localhost:8888/shipping-service/api/v1/ships",
    backendOrderEventtHost:"http://localhost:8888/order-service/api/v1/orders/events/all",
    backendProductMostOrderedHost:"http://localhost:8888/order-service/api/v1/orders/most-ordered-products",
    backendTop10CustomersMostOrderedHost:"http://localhost:8888/order-service/api/v1/orders/top10",
    backendCustomerExtistHost:"http://localhost:8888/customer-service/api/v1/customers/exists-by-email"
    
};
